openapi: 3.0.0
info:
  description: |
    This is the HuBMAP Entity APIs specification
    [http://www.hubmapconsortium.org](http://www.hubmapconsortium.org)
  version: "1.0.0-oas3-test"
  title: HuBMAP Entity APIs
  termsOfService: "http://www.hubmapconsortium.org"
  contact:
    email: apiteam@hubmap.org
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: dataset
    description: Operations about dataset
    externalDocs:
      description: Find out more about our dataset
      url: "http://hubmap.org"
  - name: entity
    description: Operations about entity
    externalDocs:
      description: Find out more about our entity
      url: "http://hubmap.org"
paths:
  /entities/types:
    get:
      tags:
        - entity
      summary: Get a list of the valid entity types
      operationId: getEntityTypes
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  entity_types:
                    type: array
                    items:
                      $ref: "#/components/schemas/EntityType"
        "400":
          description: A system error occurred
        "401":
          description: The user's token has expired
  "/entities/types/{type_code}":
    get:
      tags:
        - entity
      summary: Get uuids by type code
      operationId: getEntityByType
      parameters:
        - name: type_code
          in: path
          description: code of type
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuids:
                    example: [13ceb39891c4d06fc8fb5dbb5b0c16a0, 51318fa4fff79c82d4de7b2d70e630cb]
                    type: array
                    items:
                      type: string
        "401":
          description: The user's token has expired
        "400":
          description: Invalid type code or a system error
  "/entities/{identifier}":
    get:
      tags:
        - entity
      summary: Get Entity
      operationId: getEntity
      parameters:
        - name: identifier
          in: path
          description: The unique identifier of entity.  This identifier can be a UUID, Display DOI (HBM365.KSBD.575) or DOI (365KSBD575).  This can also be the HuBMAP identifier (TEST0004, TEST0004-LK) for donors or samples.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                properties:
                  entity_node:
                    type: object
                    items:
                      $ref: "#/components/schemas/EntityNode"
        "400":
          description: Invalid entity identifier or a system error
        "401":
          description: The user's token has expired
  "/entities/{identifier}/provenance":
    get:
      tags:
        - entity
      summary: Get Provenance Data for Entity.  This returns a PROV JSON compliant representation of the entity's provenance. Refer to this document for more information regarding [PROV JSON format](https://www.w3.org/Submission/2013/SUBM-prov-json-20130424/)
      operationId: getEntityProvenance
      parameters:
        - name: identifier
          in: path
          description: The unique identifier of entity.  This identifier can be a UUID, Display DOI (HBM365.KSBD.575) or DOI (365KSBD575).  This can also be the HuBMAP identifier (TEST0004, TEST0004-LK) for donors or samples.  
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object

        "400":
          description: Invalid entity identifier or a system error
        "401":
          description: The user's token has expired
servers:
  - url: "https://uuid.hubmapconsortium.org/entity"
  - url: "http://uuid.hubmapconsortium.org/entity"
components:
  securitySchemes:
    globus_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "https://auth.globus.org/v2/oauth2/authorize"
          scopes:
            "write:entities": modify entities
            "read:entities": read entities
    api_key:
      type: apiKey
      name: api_key
      in: header
  schemas:
    EntityType:
      description: 'A list of the types of entities.'
      example: Lab, Sample, Donor, Dataset
      type: string
    EntityNode:
      description: 'The information for a single entity.  This will vary a bit given the entity type'
      type: object
      required:
        - uuid
        - doi
        - display_doi
        - entitytype
      properties:
        uuid:
          type: string
          example: b2a0b756658d295bb6b2500db707ae85
        doi:
          type: string
          example: 434SQQX764
        display_doi:
          type: string
          example: HBM:434-SQQX-764
        entitytype:
          type: string
          example: Donor, Sample, Dataset

