version: "3.7"

services:
  
  entity-api:
    environment:
      - HOST_GID=${HOST_GID:-1000}
      - HOST_UID=${HOST_UID:-1000}
    init: true
    restart: always
    volumes:
      # Mount the schema yaml file
      - "../src/schema/provenance-schema.yaml:/usr/src/app/src/schema/provenance-schema.yaml"
      # Mount the logrotate configuration file
      - "../src/entity-api.logrotate.conf:/etc/logrotate.d/entity-api"

