version: "3.7"

# Will use the hostname when talking between services on the same network
services:
  
  entity-api:
    hostname: entity-api
    container_name: entity-api
    # Map host machine port 3333 to container port 8080
    # Only root can listen on ports below 1024, we use higher-numbered ports
    # since nginx is running under non-root user hubmap
    ports:
      - "3333:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - HOST_GID=${HOST_GID:-1000}
      - HOST_UID=${HOST_UID:-1000}
    init: true
    restart: always
    volumes:
      # Mount the app config to container in order to keep it outside of the image
      - "../src/instance:/usr/src/app/src/instance"
      # Mount the logging to container
      - "../log:/usr/src/app/log"
      # Mount the schema yaml file
      - "../src/schema/provenance_schema.yaml:/usr/src/app/src/schema/provenance_schema.yaml"
      # Mount conf.d on host machine to the nginx conf.d on container
      - "./entity-api/nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - gateway_hubmap

networks:
  # This is the network created by gateway to enable communicaton between multiple docker-compose projects
  gateway_hubmap:
    external: true
