version: "3.7"

services:
  
  entity-api:
    volumes:
      # Mount the VERSION file and BUILD file
      - "../VERSION:/usr/src/app/VERSION"
      - "../BUILD:/usr/src/app/BUILD"
      # Mount the source code to container
      - "../src:/usr/src/app/src"