version: "3.7"

# Will use the hostname when talking between services on the same network
services:
  
  entity-api:
    build: ./entity-api
    # Build the image with name and tag
    image: entity-api:0.1.0
    hostname: entity-api
    container_name: entity-api
    volumes:
      # Mount the configuration to container
      - "../conf:/usr/src/app/conf"
      # Mount the logging to container
      - "../log:/usr/src/app/log"
    networks:
      - gateway_hubmap

  hubmap-neo4j:
    build: ./hubmap-neo4j
    # Build the image with name and tag
    image: hubmap-neo4j:0.1.0
    hostname: hubmap-neo4j
    container_name: hubmap-neo4j
    # Use the same port mapping for dev and prod
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      # Mount the graph db folder to container
      - "./hubmap-neo4j/hubmap.db:/usr/src/app/neo4j/data/databases/hubmap.db"
      # Mount the neo4j configuration file to container
      - "./hubmap-neo4j/neo4j.conf:/usr/src/app/neo4j/conf/neo4j.conf"
    networks:
      - gateway_hubmap

networks:
  # This is the network created by gateway to enable communicaton between multiple docker-compose projects
  gateway_hubmap:
    external: true
