version: "3.7"

services:
  
  entity-api:
    environment:
      - HOST_GID=${HOST_GID:-1000}
      - HOST_UID=${HOST_UID:-1000}
    init: true
    restart: always
    volumes:
      # Mount the source code to container
      - "../src/schema/hubmap-entities.yaml:/usr/src/app/src/schema/hubmap-entities.yaml"

