version: "3.7"

# Will use the hostname when talking between services on the same network
services:
  
  entity-api:
    build: 
      context: ./entity-api
      args:
        # The commons github branch to be used during image build (default to master if not set or null)
        - COMMONS_BRANCH=${COMMONS_BRANCH:-master}
    # Build the image with name and tag
    image: entity-api:1.7.1
    hostname: entity-api
    container_name: entity-api
    volumes:
      # Mount the app config to container in order to keep it outside of the image
      - "../src/instance:/usr/src/app/src/instance"
      # Mount the logging to container
      - "../log:/usr/src/app/log"
    networks:
      - gateway_hubmap

networks:
  # This is the network created by gateway to enable communicaton between multiple docker-compose projects
  gateway_hubmap:
    external: true
