version: "3.7"

services:
  
  entity-api:
    # Map host machine port 3333 to container port 8080
    # Only root can listen on ports below 1024, we use higher-numbered ports
    # since nginx is running under non-root user hubmap
    ports:
      - "3333:8080"
    volumes:
      # Mount the VERSION file and BUILD file
      - "../VERSION:/usr/src/app/VERSION"
      - "../BUILD:/usr/src/app/BUILD"
      # Mount the source code
      - "../src:/usr/src/app/src"