version: "3.7"

services:
  
  entity-api:
    environment:
      - HOST_GID=${HOST_GID:-1000}
      - HOST_UID=${HOST_UID:-1000}
    init: true
    restart: always
    volumes:
      # Mount the VERSION file and BUILD file
      - "../VERSION:/usr/src/app/VERSION"
      - "../BUILD:/usr/src/app/BUILD"
      # Mount the source code
      - "../src:/usr/src/app/src"
